version: "3.8"

services:

  meal-db:
    container_name: "meal-db"
    image: mysql:latest
    volumes:
    - type: volume
      source: meal-volume
      target: /var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: "pass"
      MYSQL_DATABASE: "data"

  service-1:
    container_name: "service-1"
    image: matt266/service-1
    build: ./service_1
    environment:
      DATABASE_URI: "mysql+pymysql://root:pass@meal-db:3306/data"
    restart: on-failure

  service-2:
    container_name: "service-2"
    image: matt266/service-2
    build: ./service_2

  service-3:
    container_name: "service-3"
    image: matt266/service-3
    build: ./service_3

  service-4:
    container_name: "service-4"
    image: matt266/service-4
    build: ./service_4

  meal-proxy:
    container_name: meal-proxy
    image: nginx:latest
    ports:
    - target: 80
      published: 80
      protocol: tcp
    volumes:
    - type: bind
      source: ./nginx/nginx.conf
      target: /etc/nginx/nginx.conf
    depends_on:
    - service-1

volumes:
  meal-volume:
