pipeline{
    agent any
    environment{
        DATABASE_URI=credentials("DATABASE_URI")
        DOCKERHUB_CREDENTIALS=credentials("DOCKERHUB_CREDENTIALS")
    }
    stages{
        stage('Setup'){
            steps{
                sh "cd make_meal_app && bash scripts/setup.sh"
            }
        }
        stage('Test app'){
            steps{
                sh "cd make_meal_app && bash scripts/tests.sh"
            }
        }
        stage('Builds images'){
            steps{
                sh "cd make_meal_app && bash scripts/build.sh"
            }
        }
        stage('configure VMs'){
            steps{
                sh "cd make_meal_app && bash scripts/config.sh"
            }
        }
        stage('Deploy stack'){
            steps{
                sh "cd make_meal_app && bash scripts/deploy.sh"
            }
        }
        
    }   
}